micronaut:
  application:
    name: justserve-cli
    version: "@justserveCliVersion@"
  http:
    services:
      justserve:
        url: https://www.justserve.org
    client:
      read-timeout: 20s
justserve:
  token: ${:i-need-to-be-defined}
jackson:
  deserialization:
    ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true