micronaut:
  application:
    name: fulcrum
  http:
    services:
      justserve:
        url: ${JUSTSERVE_URL:`https://www.justserve.org`}
justserve:
  token: ${JUSTSERVE_TOKEN:'i-need-to-be-defined'}
jackson:
  deserialization:
    ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true