micronaut:
  application:
    name: fulcrum
  http:
    services:
      justserve:
        url: https://www.justserve.org
        MICRONAUT_HTTP_SERVICES_JUSTSERVE_TOKEN:
jackson:
  deserialization:
    ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true