package org.justserve.model

import com.fasterxml.jackson.annotation.JsonFormat
import org.justserve.model.response.AttachmentInfo
import org.justserve.model.response.OrganizationSlim

/**
 * JustServe.Contracts.Project
 * @author Jonathan Zollinger
 * @since 0.0.1
 */
data class Project(
    var id: String?,
    var projectOwners: Array<ProjectOwner>?,
    var location: Location,
    var ownerLog: Array<ProjectOwnerLog>?,
    var projectType: ProjectType,
    var status: ProjectStatus,
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    var publishDate: String?,
    var language: String?,
    var country: String?,
    var title: String?,
    var shortDescription: String?,
    var longDescription: String?,
    var logo: String?,
    var attachments: Array<String>?,
    var attachmentInfo: Array<AttachmentInfo>?,
    var applicant: Applicant?,
    var contact: Contact?,
    var sponsor: Sponsor?,
    var representative: Representative?,
    var organization: Org?,
    var suitableAllAges: Boolean?,
    var groupProject: Boolean?,
    var volunteerRemotely: Boolean?,
    var itemDonations: Boolean?,
    var wheelchairAccessible: Boolean?,
    var indoors: Boolean?,
    var forYouthGroups: Boolean?,
    var volunteerFromAnywhere: Boolean?,
    var regionSelected: Boolean?,
    var temporaryFakeDistanceScore: Double?,
    var fakeDistanceScoreUpdate: String?,
    var skills: Array<String>?,
    var interests: Array<String>?,
    var tools: Array<String>?,
    var projectSkills: Array<Int>?,
    var projectInterests: Array<Int>?,
    var projectTools: Array<Int>?,
    var externalVolunteerURL: String?,
    var isExternalProject: Boolean?,
    var isUnlistedProject: Boolean?,
    var archivedProject: Boolean?,
    var isActive: Boolean?,
    var externalVolunteerCount: Int?,
    var externalVolunteers: Array<String>?,
    var allEventsFilled: Boolean?,
    var daysOfWeek: Array<DayOfWeek>?,
    var timesOfDay: Array<TimeOfDay>?,
    var waiverURL: String?,
    var dtl: Array<DTL>?,
    var onGoing: Array<OnGoing>?,
    var recurring: Recurring?,
    var lastChangeReason: String?,
    var escalated: String?,
    var created: String,
    var updated: String,
    var createdBy: String?,
    var deleted: Boolean,
    var deletedOn: String?,
    var deletedBy: String?,
    var firstStartDateTimeOffset: String?,
    var lastEndDateTimeOffset: String?,
    var cbfName: String?,
    var cblName: String?,
    var updatedBy: String?,
    var ubfName: String?,
    var ublName: String?,
    var volunteerCentersData: Array<OrganizationSlim>?,
    var relativityScore: Double?,
    var projectOwnerName: String?,
    var projectOwnerLastName: String?,
    var projectOwnerUserId: String?,
    var projectLocationType: ProjectLocationType?,
    var underReview: Boolean?,
)