name: GraalVM Native Image Test run and build tests
on: [pull_request]
jobs:
  build:
    name: test and compile on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MICRONAUT_HTTP_SERVICES_JUSTSERVE_TOKEN: ${{ secrets.MICRONAUT_HTTP_SERVICES_JUSTSERVE_TOKEN }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: call gradle to run tests and then compile
        run: ./gradlew test nativeCompile
      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: justserve-${{ matrix.os }}